export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="app-shell">
          <div className="container">{children}</div>
        </div>
      </body>
    </html>
  )
}
